version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv || virtualenv venv
            . venv/bin/activate
            python setup.py install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python setup.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports
